name: jaguar_martini
description: Jekyll and Hugo like static site generator that uses right mix of Markdown, HTML and Dart
version: 0.0.7-dev
homepage: https://github.com/tejainece/jaguar_martini
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^1.3.9
  jaguar_cache: ^0.2.1
  rxdart: ^0.15.0
  yaml: ^2.1.12
  stream_transform: ^0.0.9
  markd: ^0.11.4+3
  path: ^1.4.2

dev_dependencies:
  test: ^0.12.0
  stencil: ^0.0.2

