name: jaguar_hugo
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: SERAGUD <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^0.6.10

dev_dependencies:
  test: ^0.12.0
