name: jaguar_martini
description: Jekyll and Hugo like static site generator that uses right mix of Markdown, HTML and Dart
version: 0.1.0-dev
homepage: https://github.com/tejainece/jaguar_martini
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: ">=2.0.0-dev.63.0 <3.0.0"

dependencies:
  jaguar: ^2.1.1
  jaguar_cache: ^0.2.1
  rxdart: ^0.18.0
  yaml: ^2.1.12
  stream_transform: ^0.0.14
  markdown: ^2.0.1
  path: ^1.6.1

dev_dependencies:
  test: ^1.2.0
  stencil: ^0.0.2

